### ISSUE TITLE
minor code typo in linear regression : episode 2

### ISSUE THREAD

**Issue by showrav-ansary** [carpentries-incubator/machine-learning-novice-sklearn#25]
`y_data = [4,5,7,10,15]]` is causing error because of the extra ending square bracket (`]`)at line `151` of the `md` file for `y_data` list. Extra `]` has been removed in my PR #24

**Comment by vinisalazar** [comment]
Hi @showrav-ansary,

thank you for the issue. I have reviewed and approved #24 . As soon as it's approved by the other maintainers, it should be good to merge.

Please note that this lesson will be modified in the near future as we're planning an update for future workshops. This will hopefully remove errors similar to this one.

Best,
Vini

**Comment by colinsauze** [comment]
Thanks for fixing this issue @showrav-ansary. I've merged your pull request.
