### ISSUE TITLE
Use numpy for regression chapter

### ISSUE THREAD

**Issue by johncoxon** [carpentries-incubator/machine-learning-novice-sklearn#36]
I am working through the course at a colleague's recommendation, and I was surprised to see that the course was looping over variables to calculate sums instead of using numpy to do array-based calculations at https://carpentries-incubator.github.io/machine-learning-novice-sklearn/02-regression/index.html.

I think the course should be demonstrating best practice in scientific computing, and I think it would be a better approach to store all the variables in numpy arrays and then do the sum by calling functions like `np.sum(x)`, the sum of the products as `np.sum(x * y)`, etc.

**Comment by colinsauze** [comment]
The course is designed to be accessible to people who've only done an introductory carpentries python course where these concepts haven't been covered.

**Comment by johncoxon** [comment]
I genuinely think if you're introducing these tools to students before introducing numpy then you're probably not teaching the concepts in the right order, but if that's the goal then fair enough!

**Comment by colinsauze** [comment]
We're just following the Carpentries recommendations (see https://carpentries.github.io/instructor-training/05-memory/index.html) for keeping cognitive load low by not introducing too many new concepts and focussing on what our learners really need to do some machine learning.
